// src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Config } from 'fire-ng/lib/interfaces/config';
import { Layout } from 'fire-ng/lib/interfaces/layout';

import { AppService } from 'src/app/shared/app.service';

@Component({
  selector: 'blz-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  public app: Config;
  public site: Layout;

  public year: string = new Date().getFullYear().toString();

  constructor(appService: AppService) {
    const config = appService.getConfig();
    this.app = config.app;
    this.site = config.site;
  }

  ngOnInit(): void {
  }

}
<div class="footer p-10 bg-base-200 text-base-content pl-20 pr-20 footer-links">
    <ng-container *ngFor="let linkBlock of site.footerLinks">
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">
          {{ linkBlock.header }}
        </h2>
        <nav class="list-none mb-10">
          <li *ngFor="let linkItem of linkBlock.body">
            <a href="{{ linkItem.link }}" class="text-gray-600 hover:text-gray-800">
                {{ linkItem.text }}
            </a>
          </li>
        </nav>
      </div>
    </ng-container>
    <div class="md:relative md:w-250 md:mx-auto">
      <p class="text-gray-500 text-sm text-center sm:text-left py-3 md:py-0">
        Telephone: 
        <a title="Call Us" href="tel:+{{ app.phone }}" class="text-gray-600 hover:underline" target="_blank">
          {{ app.phone | phoneFormat }}
        </a>
        &nbsp;&nbsp;|&nbsp;&nbsp;
        Email:
        <a title="Email Us" href="mailto:{{ app.email }}" class="text-gray-600 hover:underline">
          {{ app.email }}
        </a>
      </p>
      <p class="text-gray-500 text-sm text-center sm:text-left py-3 md:py-0">
        &copy; {{ year }} {{ app.company }} — All Rights Reserved.
      </p>
    </div>
  </div> 
  <div class="footer pl-20 pr-20 py-4 border-t bg-base-200 text-base-content border-base-300">
    <div class="items-center grid-flow-col">
      <img class="transition-opacity group-hover:opacity-75" src="https://blazed.sirv.com/logo/Beaker-Dark.png?w=35&h=35">
      <p>
        {{ app.company }}
        <br />
        <a title="We'd love to hear your feedback!" href="https://forms.gle/f9F4SRyfpKdAHJ1R6" target="_blank" class="block md:inline text-gray-600 ml-1 group hover:text-gray-500 active:text-gray-700 pt-2 md:pt-0">
          <i class="inline-flex pl-1 group-hover:text-gray-500">
            <svg class="group-hover:opacity-75" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" class="w-3 h-3" fill="currentColor">
              <path d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"/>
            </svg>
          </i>
          Feedback?
        </a>
      </p>
    </div> 
    <div class="md:place-self-center md:justify-self-end">
      <span class="inline-flex sm:ml-auto sm:mt-0 pl-2 mt-2 justify-center sm:justify-start">
        <span class="inline-flex" *ngIf="app.social.facebook !== undefined">
          <a title="Check us out on Facebook" href="{{ app.social.facebook.url }}" target="_social" class="text-gray-500 hover:text-black">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
            </svg>
          </a>
        </span>
        <span class="inline-flex" *ngIf="app.social.twitter !== undefined">
          <a title="Check us out on Twitter" href="{{ app.social.twitter.url }}" target="_social" class="ml-3 text-gray-500 hover:text-black">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
            </svg>
          </a>
        </span>
        <span class="inline-flex" *ngIf="app.social.instagram !== undefined">
          <a title="Check us out on Instagram" href="{{ app.social.instagram.url }}" target="_social" class="ml-3 text-gray-500 hover:text-black">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
              <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
            </svg>
          </a>
        </span>
        <span class="inline-flex" *ngIf="app.social.linkedin !== undefined">
          <a title="Check us out on Linkedin" href="{{ app.social.linkedin.url }}" target="_social" class="ml-3 text-gray-500 hover:text-black">
            <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
              <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
              <circle cx="4" cy="4" r="2" stroke="none"></circle>
            </svg>
          </a>
        </span>
      </span>
    </div>
  </div>

// components/footer.vue
<script setup lang="ts">
    import { siteConfig, brandConfig, socialConfig } from "~/config/site";
    import { formatPhoneNumber } from "~/utils/format";
    const year = new Date().getFullYear();
    const date = new Date().toISOString();
</script>
<template>
    <footer class="bg-white select-none border-t">
      <div class="mx-auto max-w-screen-xl px-4 pb-6 pt-16 sm:px-6 lg:px-8 lg:pt-24">
        <div class="grid grid-cols-1 gap-8 lg:grid-cols-3">
          <div>
            <div class="flex justify-center sm:justify-start">
                <nuxt-link class="group" href="/" v-bind:title="siteConfig.name">
                    <img src="/images/beaker-dark.png" width="35" height="35" class="inline-flex group-hover:opacity-75" />
                    <span class="inline-flex text-2xl pl-2 font-bold text-gray-600 group-hover:text-gray-400">
                        {{ siteConfig.name }}
                    </span>
                </nuxt-link>
            </div>
    
            <p
              class="mt-6 max-w-md text-center leading-relaxed text-gray-500 sm:max-w-xs sm:text-left"
            >
              We turn Dreams into Reality.
            </p>
    
            <ul class="mt-8 flex justify-center gap-6 sm:justify-start md:gap-8">
              <li>
                <nuxt-link
                  v-bind:href="socialConfig.facebook"
                  rel="noreferrer"
                  target="_blank"
                  class="text-gray-700 transition hover:text-gray-700/75"
                >
                  <span class="sr-only">Facebook</span>
                  <svg
                    class="h-6 w-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </nuxt-link>
              </li>
    
              <li>
                <nuxt-link
                  v-bind:href="socialConfig.instagram"
                  rel="noreferrer"
                  target="_blank"
                  class="text-gray-700 transition hover:text-gray-700/75"
                >
                  <span class="sr-only">Instagram</span>
                  <svg
                    class="h-6 w-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </nuxt-link>
              </li>
    
              <li>
                <nuxt-link
                  v-bind:href="socialConfig.twitter"
                  rel="noreferrer"
                  target="_blank"
                  class="text-gray-700 transition hover:text-gray-700/75"
                >
                  <span class="sr-only">Twitter</span>
                  <svg
                    class="h-6 w-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"
                    />
                  </svg>
                </nuxt-link>
              </li>
    
              <li>
                <nuxt-link
                  v-bind:href="socialConfig.github"
                  rel="noreferrer"
                  target="_blank"
                  class="text-gray-700 transition hover:text-gray-700/75"
                >
                  <span class="sr-only">GitHub</span>
                  <svg
                    class="h-6 w-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                      clip-rule="evenodd"
                    />
                  </svg>
                </nuxt-link>
              </li>

            </ul>
          </div>
    
          <div
            class="grid grid-cols-1 gap-8 sm:grid-cols-2 md:grid-cols-4 lg:col-span-2"
          >
            <div class="text-center sm:text-left">
              <p class="text-lg font-medium text-gray-900">
                Company
              </p>
    
              <ul class="mt-8 space-y-4 text-sm">
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazedlabs.com/about"
                  >
                    About Us
                  </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazedlabs.com/products"
                  >
                    Products
                  </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazedlabs.com/solutions"
                  >
                    Solutions
                  </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazedlabs.com/blog"
                  >
                    Blog
                  </nuxt-link>
                </li>
              </ul>
            </div>
    
            <div class="text-center sm:text-left">
              <p class="text-lg font-medium text-gray-900">
                Our Services
              </p>
    
              <ul class="mt-8 space-y-4 text-sm">
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazed.systems/"
                  >
                    Systems Engineering
                  </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazed.xyz/"
                  >
                    Publishing
                  </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://beez.top/"
                  >
                    Marketing
                  </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazed.tel/"
                  >
                    Telecom
                  </nuxt-link>
                </li>
              </ul>
            </div>
    
            <div class="text-center sm:text-left">
              <p class="text-lg font-medium text-gray-900">
                Helpful Links
              </p>
    
              <ul class="mt-8 space-y-4 text-sm">
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazedlabs.com/faq"
                  >
                    FAQs
                </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="text-gray-700 transition hover:text-gray-700/75"
                    href="https://blazed.contact/support"
                  >
                    Support
                </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="group flex justify-left gap-1.5"
                    href="https://blazed.contact/live-chat"
                    target="_blank"
                  >
                    <span
                      class="text-gray-700 transition group-hover:text-gray-700/75"
                    >
                      Live Chat
                    </span>
    
                    <span class="relative flex h-2 w-2">
                      <span
                        class="absolute inline-flex h-full w-full animate-ping rounded-full bg-teal-400 opacity-75"
                      ></span>
                      <span
                        class="relative inline-flex h-2 w-2 rounded-full bg-teal-500"
                      ></span>
                    </span>
                  </nuxt-link>
                </li>
              </ul>
            </div>
    
            <div class="text-center sm:text-left">
              <p class="text-lg font-medium text-gray-900">
                Contact Us
              </p>
    
              <ul class="mt-8 space-y-4 text-sm">
                <li>
                  <nuxt-link
                    class="flex items-center justify-center gap-1.5 ltr:sm:justify-start rtl:sm:justify-end"
                    v-bind:href="`mailto:${brandConfig.email}`"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="h-5 w-5 shrink-0 text-gray-900"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      stroke-width="2"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"
                      />
                    </svg>
    
                    <span class="flex-1 text-gray-700">{{ brandConfig.email }}</span>
                </nuxt-link>
                </li>
    
                <li>
                  <nuxt-link
                    class="flex items-center justify-center gap-1.5 ltr:sm:justify-start rtl:sm:justify-end"
                    v-bind:href="`tel:${brandConfig.telephone}`"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      class="h-5 w-5 shrink-0 text-gray-900"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      stroke-width="2"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"
                      />
                    </svg>
    
                    <span class="flex-1 text-gray-700">
                        {{ formatPhoneNumber(brandConfig.telephone || ``) }}
                    </span>
                </nuxt-link>
                </li>
              </ul>
            </div>
          </div>
        </div>
    
        <div class="mt-12 border-t border-gray-100 pt-6">
          <div class="text-center sm:flex sm:justify-between sm:text-left">
            <p class="text-sm text-gray-500">
    
              <a
                class="inline-block text-gray-600 hover:underline transition hover:text-gray-600/75"
                href="https://blazedlabs.com/privacy"
              >
                Privacy Policy
              </a>
            </p>
    
            <p class="mt-4 text-sm text-gray-500 sm:order-first sm:mt-0">
              &copy;<time v-bind:date-time="date">{{ year }}</time> {{ brandConfig.company }}. All Rights Reserved.
            </p>
          </div>
        </div>
      </div>
    </footer>
  </template>
